pipeline {
    agent any

    tools {
        maven 'maven-3.9'
    }

    environment {
        IMAGE = "spring-jenkins-app:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                sh "mvn -B -DskipTests clean package"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE} ."
            }
        }

        stage('Load Image into Minikube') {
            steps {
                sh "minikube image load ${IMAGE}"
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh "kubectl apply -f k8s"
            }
        }
    }
}
